# Welcome to AdvancedWhitelist.
## Once configured and permissions set, it will give the smoothest experience for managing access for entire teams. 
### Everything you can configure here in the file, can also be checked and configured in game with various commands.
#### All commands, permissions, and aliases are listed in the help menu at "/awl help <number>"
#
# Important: To use any of the commands in game, you will need the permission advancedwhitelist.admin
#
# Initially the Whitelist will be disabled, but you can enable it here at "whitelist_enabled" and reload the config with "/awl reload" or you can use "/awl on" from console, or in-game if you have the permission.
#
# Without any config changes, "advancedwhitelist.bypass.operators" is the only permission that will always have access to the server regardless of below settings.
## Recommended Note: This permission should be restricted to a Server Owner and the most trusted Staff/Admins/Operators, whatever term your server uses for it.
#
# There are other Permissions that will allow access if the below access are turned on.
## The permission is "advancedwhitelist.bypass.<perm>" where <perm> is one of the following access options.
### <ProjectTeam, Staff, Tester, Alternate, Other> Access
#### You can choose how you want to use the permissions for access.
##### Each perm/access is separate from each other, so if tester access is enabled but staff isn't, staff won't be able to access it unless they also have the perm.
#
# This is still a WhiteList plugin, so you can still add players names either in the config or using the in-game commands.
## For the list to be effective, you will need to turn on the Config Access option.
#
# There's also a command setup so that it will restrict the current online players to only those that are allowed by the Whitelist
## It will first attempt to send the Non-Whitelisted player to the Lobby/Hub server specified in the config below at "server_to_send_to".
### If they're currently on that server, or if it fails to send for some reason, it will then kick the player.
#
# During the send and kick, there's an initial Broadcast message, which can be configured below.
## There's a message that's sent to the player just before they're sent to the lobby/hub server.
### There's a separate kick message that's configurable for the players.
#### Sorry for other servers, the message set is for the server/network the plugin was developed for.
#
# This plugin is also setup with a cooldown from when the plugin starts, generally when the server starts, to when players can connect.
## This has been added so that you can allow a server to settle before players rush to join again. But if you don't want this, it can also be turned off.
### It's on by default, but can be turned on, and the amount of time to wait can also be changed.
#### There are two exceptions. Users with the Operators Bypass perm will be able to connect at one-third (1/3) the time specified to allow the highest admins to connect and make changes as needed, such as if a server needs to be set to whitelist.
#### Second, the ProjectTeam Bypass perm will be able to connect at half (1/2) the time specified for the same reason.
#
# Note: All times are based on seconds.
#
# Don't change the Config Version
config_version_dont_change: "2.0"
whitelisted:
- "ExampleNameThatWouldHaveAccessIfConfigAccessIsOn_PleaseReplaceThis"
config:
   access_enabled:
      whitelist: false
# If enabled, will allow the players in whitelisted to connect to the server.
      config_access: false
# If whitelist_enabled above is false, the below whitelist options won't matter.
# Each Access below is it's own permission and some can be on while others are off.
# The permissions will be AdvancedWhiteList.Bypass.<Team> - Where <Team> equals ProjectTeam, Staff, Tester, Alternate, Other, etc.
      teams:
         projectteam: false
         staff: false
         tester: false
         alternate: false
         other: false
   messages:
# Message given to player when they weren't allowed to connect to the server.
      not_whitelisted_message: "&eSorry, the server has been put into Whitelist mode, and you're not whitelisted at the moment. If you feel this is a mistake, please contact the proper staff to get it corrected. If you aren't part of the whitelist, feel free to join one of our other servers. The available lobby servers are play.ham5teak.xyz and play.ham5teak.net.au while we have various modes to play in, including Survival, Semi-Vanilla Survival, Skyblocks, Creative, Factions, Prison, and Minigames. Don't forget that some of them will have new Australian versions as well. :)"
# Broadcast sent before players start getting kicked.
      send_or_kick_broadcast_message: "&eSorry, the server is currently in Whitelist mode, and those that are not whitelisted will be sent back to the lobby, if you do get sent, please enjoy one of our other modes of Survival, Semi-Vanilla Survival, Skyblocks, Creative, Factions, Prison, and Minigames! :)"
# Sent to players just before they get kicked from the server when they aren't Whitelisted.
      send_message: "&eSorry, the server has been put into Whitelist mode, and you're not whitelisted at the moment. If you feel this is a mistake, please contact the proper staff to get it corrected. If you aren't part of the whitelist, feel free to join one of our other servers. The available lobby servers are play.ham5teak.xyz and play.ham5teak.net.au while we have various modes to play in, including Survival, Semi-Vanilla Survival, Skyblocks, Creative, Factions, Prison, and Minigames. Don't forget that some of them will have new Australian versions as well. :)"
# Used in case send fails
      kick_message: "&eSorry, the server has been put into Whitelist mode, and you're not whitelisted at the moment. If you feel this is a mistake, please contact the proper staff to get it corrected. If you aren't part of the whitelist, feel free to join one of our other servers. The available lobby servers are play.ham5teak.xyz and play.ham5teak.net.au while we have various modes to play in, including Survival, Semi-Vanilla Survival, Skyblocks, Creative, Factions, Prison, and Minigames. Don't forget that some of them will have new Australian versions as well. :)"
   durations:
      server_cooldown_duration: 90
      delay_before_starting_kicks: 4
      kick_delay_per_player: 1
   misc:
      server_cooldown: true
# This is the server name to be used according to Bungeecord that the players will go to when kicked.
      server_to_send_to: lobby
      allow_op_and_star_bypass: false
gui:
   enabled_row1:
      true: green_stained_glass_pane
      false: red_stained_glass_pane
   messages_row2:
      lobby: compass
      not_whitelisted_message: paper
      send_or_kick_broadcast_message: paper
      send_message: paper
      kick_message: paper
   durations_row3:
      server_cooldown_duration: clock
      delay_before_starting_kicks: clock
      kick_delay_per_player: clock
   commands_row4:
      status: book
      whitelisted_config_list: writable_book
      add: emerald
      remove: redstone
      add_all_online: emerald_block
      remove_all: redstone_block
      send_players_enforce_whitelist: barrier
      restart_server: barrier
   anvil_item: name_tag
   
   
   
   
   
   
   